### ISSUE TITLE
Database Cache mode

### ISSUE THREAD

**Issue by Gotrek65** [NuVotifier/NuVotifier#127]
It would be fantastic if we could have a database mode for vote caching. So if say you have multiple servers listening to votes you don't duplicate votes or if 1 listener goes down and the other is up you don't have 2 separate cached vote lists that aren't synchronized.

**Comment by Ichbinjoe** [comment]
I don't see a massive benefit for the increased complexity that database caching would bring.

Most people (even larger servers) don't run redundant Votifier instances (through what I could only assume is round robin A records). Of course this isn't true everywhere, but has been for all large server installations I've been contracted to work on.

Even if you were to have redundant Votifier instances, your votes shouldn't ever be duplicated. Sure they won't be in sync, but at no time should both of the redundant instances contain the same vote instance - the vote will be sent to one of the two connections and be cached in that list. The server list shouldn't resend for each A record. If you are still doing something like a HAProxy load balance situation, only one server will ever have the record.

You have a point that the lists are not synchronized - and that this wouldn't work for a pure cloud situation when you have quickly cycling frontend forwarding proxies.

Now that I think about it, I'm trying to think of a case where votes would be cached in a multi-forwarder situation. Caching is only used in pluginMessaging mode. PluginMessaging's special features break down when it is not on the sole 'head' proxy of the network. They don't work. I don't claim that they work, its never been supported, and never will be because usually when servers get to that scale, they have developers which can program special forwarding mechanics for them if they really need it. PluginMessaging could work in the pure fanout situation and _would_ cache when one of the servers did not have players on it which were connected through that proxy. But beyond that I can't think of any conditions where caching would be required in a multi-proxy/forwarder setup.

Am I missing some case you are thinking of here? I'm not a fan of adding needless complexity, which to me this feels like.

Of course, if someone wants to write + pull request it, feel free! I would probably accept it.

**Comment by Ichbinjoe** [comment]
This is going to be a non-fix from us - feel free to reopen with more arguments.
