### ISSUE TITLE
Not able to to setup voting on my network correctly.

### ISSUE THREAD

**Issue by SilentRoses** [NuVotifier/NuVotifier#164]
Bungee config: https://pastebin.com/Z6n8pDes
Hub config: https://pastebin.com/QCtmuJEz
Opsb config: https://pastebin.com/at0WXWbm
(i've only sent 3 as the whole 12 wouldnt be fun to go through)

Error
> [NuVotifier]: Unable to send vote to localhost/127.0.0.1:8193. Will retry sending in 8 second(s).

All ports are open so that's why i'm a lil confused.

If you're able to please contact me on discord as i'm more active there.
Discord: SilentRoses#1234

**Comment by Ichbinjoe** [comment]
Please send logs for all servers.

**Comment by SilentRoses** [comment]
HUB: [Hub.log](https://github.com/NuVotifier/NuVotifier/files/3999077/Hub.log)
BUNGEE: [Bungee.log](https://github.com/NuVotifier/NuVotifier/files/3999078/Bungee.log)
OPSB: [Opsb.log](https://github.com/NuVotifier/NuVotifier/files/3999082/Opsb.log)

**Comment by SilentRoses** [comment]
Not sure if you have an official discord but if u do could i join it please?

**Comment by Ichbinjoe** [comment]
You are running NuVotifier 3.0.0-SNAPSHOT. Since this appears to be a configuration error (these sorts of problems always are) and you are running an experimental version, I provide absolutely zero support. Please see NuVotifier's Spigot page for more of an explanation on my support policy as well as some links which may help you diagnose your problem:  https://www.spigotmc.org/resources/nuvotifier.13449/

**Comment by SilentRoses** [comment]
What? i'm not? i'm running 2.5.3

**Comment by SilentRoses** [comment]
I couldn't redownload it until just now too cause the download link was broken :P
