### ISSUE TITLE
NuVotifier causes server overload due to stdout backpressure / NuVotifier doesn't properly loadshed when sent a large amount of bogus connections

### ISSUE THREAD

**Issue by Leonardo-Fiori** [NuVotifier/NuVotifier#170]
I need to clear the votes cache because i tried to stress test my server with a web stresser. It sent hundreds of thousands of TCP requests. OVH DDoS mitigation worked well but then i tried to attack on the votifier port votifier "exploded". 

Console got flooded with lots of malformed votes requests, or also "Failed to mark a promise as failure because it has succeeded already" errors when i tried to change votifier's port. The attack stopped some minutes ago but the votes are still coming!

1) How to clear all cached requests?
2) How to prevent this kind of attacks? It was super effective against OVH DDoS mitigation

**Comment by Ichbinjoe** [comment]
How were you executing this attack? This is a legitimate concern if any of those votes are legitimate. They should not be.

1. Can you elaborate on what you are referring to by "cached requests"? Are these legitimate votes waiting to be forwarded or are these half / full open TCP sockets....?

2. End of the day without ddos mitigation fronting it votifier still only exists on one box as a singleish threaded daemon (with async io, allowing it to handle multiple requests concurrently). This is by design. It protects against trivial DDOS (which the original votifier was vulnerable to). We can increase the number of handling threads potentially, however we will probably run into an upper bound of compute time. Potentially something like fail2ban would help a lot with this.

**Comment by Leonardo-Fiori** [comment]
1. I stopped the stress test, the servers stopped sending tcp packets to my server, but nuvotifier was still busy elaborating all the malformed requests he received spitting out exceptions on exceptions, and eventually crashing the whole server. I even deleted all the nuvotifier files and let them regenerate with a restart but once the plugin started, exception started flowing. Eventually, after some hours, it stopped.

2. The problem are not threads. It handled quite well compared to original votifier. The problem is that it does not properly drop malformed vote packets. I just sent some random tcp requests on the port and it went crazy. It was listening to each request. And i was sending thousands.  My gameserver is hosted on SoYouStart (OVH) and it has a very strong anti ddos protection. I tested the same stuff also on the game port (25565), the anti ddos service triggered before server crash and mitigated the attack in a perfect way. Unfortunately it's not the same for nuvotifier. The load it generates is so high that it probably will crash the server before mitigation occours.

The service i use for stressing my server is a panel used to send http or tcp requests for stress testing, it has some various working modes. I think some childish users could also abuse it in this way.

**Comment by Ichbinjoe** [comment]
ACK, will research this more when I get home. This is 100% a problem that needs fixed. I want to understand more of what's going on in kernel land to really understand what the right way to mitigate this is. Could you give me the following:

Operating system w/ kernel version if on Linux. You can get this by running `uname -a` in a shell.

NuVotifier configuration of frontend server

Output of `sysctl net.ipv4`

Server logs

Feel free to join the support discord to share me these directly( link coming in edit)

**Comment by Ichbinjoe** [comment]
Also to answer your issue quickly: the problem isnt what you are suggesting: we handle malformed packets by dropping them, but it comes with an accompanying exception which is logged which is my suspicion as to why things fell over. As for why the massive TCP queue, that's why I want this info :)

**Comment by Ichbinjoe** [comment]
Alright so now that I have more time to think about this, I think your 'panel' did not stop connecting for some time. If you stopped the JVM then restarted it, Linux will have closed the accept queue for TCP connections and reopened it, clearing the queue of requests. This is the case no matter what happens to the process - whenever a process dies in any way the kernel will clear this up. Once the JVM was restarted and a new bind was made, this is a new queue - all future connections arrived at the server after the new bind was made. NuVotifier does not set any flags which would make this not the case: https://github.com/NuVotifier/NuVotifier/blob/master/common/src/main/java/com/vexsoftware/votifier/net/VotifierServerBootstrap.java#L43

So that's why restarting appeared to cause continual grief - you were still under attack.

As for why the server fell over to begin with, current theory is either the cost of doing the RSA decryption on all data coming in (which is a very expensive operation cpu time wise) or that printing the errors caused backpressure on any logging we were doing (making the logging wait until it was able to flush logs to disk). The differentiator here is probably how much CPU was being used during the attack - if a core was at 100%, then its probably cost of RSA decryption / other expensive stuff we do. Otherwise, it was probably due to logging (since that operation just kind of turns into waiting until we have enough space in a logging buffer).

We can do a few things here to help improve performance:

+ Drastically reduce the amount of logging we do when something goes wrong with the protocol
+ Start assigning health scores to IP address which connect and use that to add requests to a priority queue for actually processing the socket. Successful decryptions would add to the score and unsuccessful decryption would lower it. This would ensure that IPs which previously had a high reputational score are processed above IPs which previously had no contact and then IPs which are known to have bad decryptions are even lower than IPs with no reputation. We can probably even CIDR distance this... hosts around other hosts with high reputation will probably also be good hosts.
+ Discourage use of v1 (which by design _must_ try a RSA decryption on all data sent) [long shot]
+ Discourage use of v2 (which also by design _must_ at least attempt to parse the message as JSON. This is far cheaper, but suboptimal)

NuVotifier 3 will come with a backconnect protocol, not requiring servers to open a separate votifier port (each voting website will instead have an endpoint). This would also solve this problem and cut down on errors servers see.

**Comment by Leonardo-Fiori** [comment]
>NuVotifier 3 will come with a backconnect protocol, not requiring servers to open a separate votifier port (each voting website will instead have an endpoint). This would also solve this problem and cut down on errors servers see.
Well, but how many lists will support this?

> Drastically reduce the amount of logging we do when something goes wrong with the protocol
This would definetly help

> Start assigning health scores to IP address which connect and use that to add requests to a priority queue for actually processing the socket. Successful decryptions would add to the score and unsuccessful decryption would lower it. This would ensure that IPs which previously had a high reputational score are processed above IPs which previously had no contact and then IPs which are known to have bad decryptions are even lower than IPs with no reputation. We can probably even CIDR distance this... hosts around other hosts with high reputation will probably also be good hosts.

This would be a great solution.

For now i think that ill try to setup tcpshield or something like that!

**Comment by Ichbinjoe** [comment]
re: how many lists will support - goal is to have a few major ones support it. Lists are interested in better tech as the support for servers setting up voting is intense.

**Comment by astei** [comment]
Could you try building the latest version of NuVotifier from master and letting me know if this issue comes up again?

**Comment by astei** [comment]
@Leonardo-Fiori Can you please confirm this is still an issue with the latest version in `master`?

**Comment by Leonardo-Fiori** [comment]
Unfortunately I have no more access to the tool that I used to stress test my server. I could try with the stupid free ddos thingies that kids usually try to use to ddos servers but I don't quite like putting my server IP inside those 😂

Do you know any good testing solution? I am interested in knowing if this is fixed too

**Comment by astei** [comment]
I'm going to consider this issue unfixed for now then and will dig into this some more. I have some generic tools that are able to easily spam a Votifier instance with nonsense requests and I still observe high CPU usage with it.

Of course the long-term solution is a new protocol not vulnerable to any of these issues in the first place.

**Comment by astei** [comment]
I'm confident this issue is fixed now.
