### ISSUE TITLE
Warning on Plugin Disable

### ISSUE THREAD

**Issue by Intriguing-RC** [NuVotifier/NuVotifier#201]
**VERSION**: 2.7.1
**LOGS**: https://pastebin.com/w3xL9enu
**DESCRIPTION**: Getting a warning on plugin disable. I am not sure if this is a configuration issue or not.

**Comment by astei** [comment]
You didn't even better to keep the template. -_-

**Comment by astei** [comment]
Closing because:

* this is a geriatric Minecraft version
* you are using some mystery meat closed-source fork of Paper and I'm not going to be touching that
* you tried to disable the plugin (if this was during server shutdown, that is fine, but not if you decided to arbitrarily reload the plugin without using the `/nvreload` command)

You can ignore the error for now, but [never try to reload the plugin through a "plugin manager" or Bukkit /reload](https://github.com/NuVotifier/NuVotifier/wiki/Troubleshooting-Guide#i-used-reload-or-plugman-on-nuvotifier-and-now-it-doesnt-work).

**Comment by astei** [comment]
For the record, the reason the error happens is because it is a bug in CraftBukkit/Spigot, not NuVotifier. This works fine on modern versions of CB, it works fine on BungeeCord, and it works fine on Velocity.
