### ISSUE TITLE
Suggestion: Logging IPs of Vote websites

### ISSUE THREAD

**Issue by TomLewis** [NuVotifier/NuVotifier#211]
Log Ip's of vote website requests.

Reason; Some vote websites need to use the GS4 UDP query to find online players, there is currently a bug opening this GS4 UDP Query up to the entire world that allows anyone to take down your bungee, and requires firewalling trusted sources (Vote websites).
Vote websites use a combination of technology to track servers, They all fall back to the SLP TCP, but when available they use the Query method as this allows them to get the actual player names of people on the server.
Yes the GS4 is not part of votifier, but there is no easy way to find out what IP's vote websites use to Query your minecraft server for its player count etc, yes votifier only accepts incoming requests and its not to do with vote websites being able to read the online players, but this is only a small log that is being requested, you already log these votes, please just add in logging where the votes are coming from with thier IP.
Then this information can be used in the firewall to allow only vote sites to use the Gs4 Query on our servers and not be attacked.

The very simple act of logging what IP's the vote websites use to when people vote, will help thousands of people solve a giant bug with all bungee servers that want to use GS4 Query.

I have had to create a new ticket as the replies I got to the existing ticket were too close minded in not understanding what the request was for or the reason.

**Comment by astei** [comment]
Continuing to preach about your GS4 UDP query problems to us isn't going to get it fixed any more quickly, particularly because we don't maintain that code (that's BungeeCord).

NuVotifier by default already logs vote attempts if `debug: true` is on (and it is on by default - fix your config if it isn't). I am now closing (and locking) this issue. If you talk about this again, you'll be locked out of communicating with us on this repository.
