### ISSUE TITLE
[Enhancement] Convert to user playername to lowercase

### ISSUE THREAD

**Issue by F9Alejandro** [NuVotifier/NuVotifier#220]
Saves on user confusion and accidental caps/lowercase when voting on vote sites, also ensures players get their votes.

This is extremely helpful since Mojang will not allow duplicate usernames with mixed casing. Ex. I have the username Fang_Shadow, and with another account I try changing the name to fang_shadow. When the lookup happens for username availability it comes up with already in use.

Additionally since we are using offlineplayer uuid generation we can assume that there won't be a duplicate with different casing so we can just convert the usernames to lowercase or uppercase to be sure that the uuid doesn't fluctuate between Fang an fang.

**Comment by astei** [comment]
NuVotifier follows the behavior of the original Votifier here. We do not modify votes. And especially as you mention "offlineplayer uuid generation" the only use case for this seems to be to make voting on offline-mode servers easier. Offline mode is too much trouble for me to support, even if I otherwise am perfectly okay with pirating the game.
