### ISSUE TITLE
Jenkins has incorrect archive artifacts setup causing failed builds.

### ISSUE THREAD

**Issue by andrewkm** [NuVotifier/NuVotifier#299]
https://ci.velocitypowered.com/job/NuVotifier/
```
Archiving artifacts
‘universal/build/libs/nuvotifier.jar’ doesn’t match anything: ‘universal’ exists but not ‘universal/build/libs/nuvotifier.jar’
ERROR: Step ‘Archive the artifacts’ failed: No artifacts found that match the file pattern "universal/build/libs/nuvotifier.jar". Configuration error?
Finished: FAILURE
```

**Comment by JOO200** [comment]
Caused by my PR #295 .

I already discussed the CI and Maven Repo topic with @Ichbinjoe on Discord but I missed the existing Jenkins build job for that. 

My changes are designed for a jfrog artifactory. I can change and pr it to the default maven plugin but I can't test the Jenkins Pipeline. @astei - can you give feedback here?
