### ISSUE TITLE
Folia support for NuVotifier?

### ISSUE THREAD

**Issue by Agaloth** [NuVotifier/NuVotifier#321]
Here is the repo link: https://github.com/PaperMC/Folia

**__Here is a summary of everything made with ChatGPT to save some time:__**

__For plugin developers, there are a few key takeaways from the given text:__

1. Folia introduces regionised multithreading, which means that plugins will require modification to function properly. Plugin developers should expect compatibility with existing plugins to be at zero.

2. Folia introduces new API additions, such as the RegionisedScheduler and EntityScheduler, which can help plugins run on the correct thread context.

3. To ensure compatibility with Folia, plugin developers must mark their plugin as compatible by placing "folia-supported: true" in the plugin.yml file. Additionally, plugins must take advantage of the RegionisedScheduler and EntityScheduler API to ensure correct behavior.

4. Plugins should not assume that they can access or modify data in other regions, as Folia regions tick in parallel and do not share data. Plugin developers should take advantage of the upcoming thread-check API to ensure correct behavior.

5. There are currently broken API, including the scoreboard API, and planned API changes, such as super aggressive thread checks, which may impact plugin development.

Overall, plugin developers should be prepared for significant changes in their plugins to ensure compatibility with Folia. They should take advantage of the new API additions and mark their plugin as compatible to ensure correct behavior. Additionally, they should be aware of the limitations and rules of Folia's regionised multithreading to avoid bugs and errors in their plugins.

**Comment by astei** [comment]
For your impersonal approach to telling me "pls add Folia support", I have taken the pleasure of having ChatGPT generate a response:

As an AI language model, ChatGPT has limitations in providing accurate context to a GitHub issue. Its responses are generated based on patterns and correlations found in large datasets, and may not always take into account the specific details and nuances of the issue at hand. Relying solely on ChatGPT for context can result in misunderstandings and miscommunications, ultimately hindering the productivity and efficiency of issue resolution.

Additionally, I would like to mention that "Folia" represents a major breaking change, and while I was present during its creation, there is no clear upgrade path. While I do agree with the changes that are being made, it is important to recognize that such changes can pose significant challenges and require careful consideration and planning.

Lastly, I want to note that while I have been involved in the Minecraft scene, I have many other commitments and am not very active in that space. Therefore, I may not be able to devote a significant amount of time or resources to addressing the GitHub issue at hand. It is important for all parties involved to recognize and respect each other's limitations and constraints in order to achieve the best possible outcome.

**Comment by Agaloth** [comment]
Sorry for the spam, that wasn't my main intention, I just want to make sure all plugin developers are aware of it and was mainly looking to see if it was possible to be added in the near future. I know that this will require tons of changes and won't be a thing that will be added quickly.

**Comment by Loving11ish** [comment]
Hello, my friend has made a fork of NuVotifier and added full support for Folia now!  Would you like me to get him to make a PR fro it?
