### ISSUE TITLE
Problem with server lists

### ISSUE THREAD

**Issue by Eiple** [NuVotifier/NuVotifier#60]
I have 1 issue,I have read the guide, i'm trying to set up bungee proxy voting, and the "enableExternal: " is missing from my NuVotifier configs on my spigot servers, do i need to add it manually or is it located elsewhere? please help me solve this.
I followed the tutorial from youtube and in theory it is working in this site

mctools.org  (works testing with any port)

but in planet minecraft or minecraft forums I get an error
ss: http://prntscr.com/i58hnc

**Comment by Ichbinjoe** [comment]
enableExternal was removed because it caused too much confusion for users with minimal security benefit. 

As for the error, make sure you follow what the error says:
+ Make sure nuvotifier is running
+ Make sure nuvotifier reports binding to the votifier port
+ Make sure nuvotifier isn't being blocked by a firewall

If you still can't figure it out, reply with your configurations and startup logs from your bungeecord server.

**Comment by Eiple** [comment]
Still the same
firewall is off atm
Bungee config : https://pastebin.com/XMzUJyWd
startup logs : https://pastebin.com/Sa4Uc9hJ

**Comment by Ichbinjoe** [comment]
Yep! Was about to point that out. Glad you figured it out!
